# KEYWORDS = [
#   "SaaS",
#   "MVP",
#   "early-stage startup",
#   "product launch",
#   "prototype",
#   "software startup",
#   "Artificial Intelligence",
#   "AI-powered",
#   "Machine Learning",
#   "Generative AI",
#   "NLP",
#   "Full-stack development",
#   "Mobile app",
#   "MERN stack",
#   "React Native",
#   "Next.js",
#   "Flutter",
#   "Automation tools",
#   "Business automation",
#   "Workflow automation",
#   "Zapier alternative",
#   "Pre-seed",
#   "Seed funding",
#   "B2B SaaS",
#   "YC-backed",
#   "Tech startup",
#   "bootstrapped startup",
#   "venture-backed",
#   "startup incubator",
#   "startup accelerator",
#   "Series A funding",
#   "startup ecosystem",
#   "founder-led",
#   "startup pitch",
#   "startup mentorship",
#   "lean startup",
#   "tech founders",
#   "early traction",
#   "startup growth",
#   "backend development",
#   "frontend development",
#   "serverless architecture",
#   "DevOps",
#   "CI/CD",
#   "GraphQL",
#   "TypeScript",
#   "Node.js",
#   "Jamstack",
#   "API-first",
#   "web app development",
#   "cross-platform app",
#   "software engineering",
#   "cloud engineering",
#   "agile development",
#   "AI startup",
#   "deep learning",
#   "computer vision",
#   "AI chatbot",
#   "LLM-powered",
#   "predictive analytics",
#   "data science",
#   "data pipeline",
#   "AI automation",
#   "AI integration",
#   "AI-as-a-Service",
#   "edge AI",
#   "machine intelligence",
#   "ML models",
#   "AI agents",
#   "AI tools",
#   "no-code platform",
#   "low-code solution",
#   "SaaS platform",
#   "cloud SaaS",
#   "vertical SaaS",
#   "API product",
#   "developer tool",
#   "tech-enabled service",
#   "PaaS",
#   "cloud-native app",
#   "B2C SaaS",
#   "digital product",
#   "early access app",
#   "beta launch",
#   "startup toolkit",
#   "process automation",
#   "CRM software",
#   "HR tech",
#   "Fintech SaaS",
#   "vertical B2B",
#   "B2B software",
#   "ERP solution",
#   "SaaS tool for SMBs",
#   "SMB automation",
#   "marketing automation",
#   "sales enablement",
#   "business workflow",
#   "digital transformation",
#   "cloud infrastructure",
#   "AWS-based",
#   "cloud-native startup",
#   "Edge computing",
#   "multitenant SaaS",
#   "microservices architecture",
#   "containerized app",
#   "Kubernetes-based",
#   "cloud computing",
#   "scalable architecture",
#   "infrastructure-as-code",
#   "EdTech",
#   "HealthTech",
#   "LegalTech",
#   "PropTech",
#   "FinTech",
#   "AgriTech",
#   "ClimateTech",
#   "SaaS founders",
#   "early adopters",
#   "technical co-founder",
#   "SaaS MVP",
#   "founder stories",
#   "open-source startup",
#   "freemium SaaS",
#   "product-led growth",
#   "startup founders",
#   "LLM-as-a-Service",
#   "AI-based SaaS",
#   "AI infrastructure",
#   "foundation models",
#   "startup launch",
#   "disruptive startup",
#   "founding team",
#   "idea-stage startup",
#   "technical founder",
#   "cross-platform app",
#   "JavaScript development",
#   "micro-frontend",
#   "responsive app",
#   "progressive web app",
#   "hybrid app",
#   "API gateway",
#   "cloud SaaS",
#   "multi-cloud architecture",
#   "load balancing",
#   "observability",
#   "Sentry",
#   "error monitoring",
#   "feature flagging",
#   "cloud SaaS",
#   "freemium model",
#   "SaaS metrics",
#   "ARR",
#   "churn reduction",
#   "retention tools",
#   "startup revenue",
#   "pricing experiments",
#   "customer success",
#   "founder-market fit",
#   "SaaS playbook",
#   "InsurTech",
#   "GovTech",
#   "HRTech",
#   "TravelTech",
#   "FoodTech",
#   "AI in Healthcare",
#   "AI in Finance",
#   "AI in Education",
#   "productized service",
#   "no-code automation",
#   "low-code automation",
#   "task automation",
#   "SaaS automation",
#   "internal tools",
#   "productivity SaaS",
#   "internal dashboard",
#   "admin panel builder",
#   "ops automation",
#   "integration platform",
#   "BPM tools",
#   "beta access",
#   "user onboarding",
#   "private beta",
#   "public launch",
#   "product feedback",
#   "user engagement",
#   "product analytics",
#   "startup CTO",
#   "growth hacking",
#   "go-to-market",
#   "SaaS for startups",
#   "SaaS for SMBs",
#   "developer-first",
#   "community-led growth",
#   "async tools",
#   "remote-first startup",
#   "cloud-first startup",
#   "API economy",
#   "Startup ecosystem mapping",
#   "Startup market entry",
#   "Startup validation",
#   "Minimum Viable Product (MVP) development",
#   "Product-market fit",
#   "Go-to-market strategy",
#   "Customer acquisition",
#   "User experience (UX) design",
#   "User interface (UI) design",
#   "Growth marketing",
#   "Digital marketing for startups",
#   "Startup legal advice",
#   "Startup accounting",
#   "Remote work tools",
#   "Distributed teams",
#   "Future of work tech",
#   "Business model innovation",
#   "Value proposition design",
#   "Lean canvas",
#   "Business plan development",
#   "Startup pitching",
#   "Investor relations",
#   "Exit strategy",
#   "Acquisition target",
#   "Bootstrapped business",
#   "Self-funded startup",
#   "Pre-seed acceleration",
#   "Seed stage investment",
#   "Series B funding",
#   "Unicorn startup",
#   "Decacorn startup",
#   "Startup valuation",
#   "Convertible note",
#   "SAFE note",
#   "Angel investing",
#   "Venture capital firm",
#   "Private equity",
#   "Crowdfunding for startups",
#   "Startup grants",
#   "Incubator programs",
#   "Accelerator programs",
#   "Mentorship for founders",
#   "Founder networking",
#   "Tech founder community",
#   "Startup best practices",
#   "Disruptive innovation",
#   "Market disruption",
#   "Competitive advantage",
#   "Intellectual property (IP) for startups",
#   "Patent application",
#   "Trademark registration",
#   "Legal tech for startups",
#   "Financial modeling for startups",
#   "Unit economics",
#   "Customer lifetime value (CLTV)",
#   "Customer acquisition cost (CAC)",
#   "Churn rate reduction",
#   "Subscription economy",
#   "Recurring revenue",
#   "SaaS sales",
#   "SaaS marketing",
#   "Product analytics",
#   "User behavior analytics",
#   "A/B testing",
#   "Conversion rate optimization (CRO)",
#   "Customer relationship management (CRM)",
#   "Sales automation",
#   "Marketing automation platforms",
#   "Customer support tools",
#   "Help desk software",
#   "Knowledge base software",
#   "Community building for startups",
#   "Developer community",
#   "Open-source community",
#   "Tech talent acquisition",
#   "Hiring for startups",
#   "Startup culture",
#   "Employee stock options (ESOPs)",
#   "HR software for startups",
#   "Payroll processing for startups",
#   "Compliance for tech startups",
#   "Data privacy regulations (GDPR, CCPA)",
#   "Cybersecurity for startups",
#   "Risk management for startups",
#   "Web3 startups",
#   "Blockchain technology",
#   "Decentralized applications (dApps)",
#   "NFT platforms",
#   "Cryptocurrency startups",
#   "Metaverse development",
#   "Virtual reality (VR)",
#   "Augmented reality (AR)",
#   "Extended reality (XR)",
#   "Spatial computing",
#   "Quantum computing",
#   "Biotechnology startups",
#   "Genomics tech",
#   "Robotics startups",
#   "Automation robotics",
#   "Industrial automation",
#   "IoT (Internet of Things) solutions",
#   "Smart devices",
#   "Connected devices",
#   "Embedded systems",
#   "Computer vision applications",
#   "Natural Language Understanding (NLU)",
#   "Speech recognition",
#   "Voice AI",
#   "Reinforcement learning",
#   "Predictive modeling",
#   "Data analytics tools",
#   "Business intelligence (BI)",
#   "Data visualization",
#   "Big data solutions",
#   "Data warehousing",
#   "Data lakes",
#   "Real-time data processing",
#   "Machine learning operations (MLOps)",
#   "AI model deployment",
#   "AI ethics",
#   "Responsible AI",
#   "Generative art",
#   "AI content generation",
#   "Code generation AI",
#   "Low-code development platforms",
#   "No-code application building",
#   "Citizen development",
#   "API integration",
#   "Microservices architecture patterns",
#   "Serverless computing",
#   "Container orchestration (e.g., Docker, Kubernetes)",
#   "Cloud security",
#   "Data encryption",
#   "Identity and access management (IAM)",
#   "Security information and event management (SIEM)",
#   "DevSecOps",
#   "Site reliability engineering (SRE)",
#   "Performance monitoring",
#   "Scalability solutions",
#   "High availability systems",
#   "Disaster recovery planning",
#   "Edge AI",
#   "Fog computing",
#   "Hybrid cloud solutions",
#   "Multi-cloud strategy",
#   "Cloud cost optimization",
#   "Green computing",
#   "Sustainable tech",
#   "API design",
#   "GraphQL API",
#   "REST API",
#   "Server-side rendering (SSR)",
#   "Client-side rendering (CSR)",
#   "Static site generation (SSG)",
#   "Headless CMS",
#   "WebRTC",
#   "WebAssembly (WASM)",
#   "Progressive Web Apps (PWAs)",
#   "Mobile-first design",
#   "Responsive web design",
#   "UX research",
#   "Prototyping tools",
#   "Wireframing",
#   "User testing",
#   "Usability testing",
#   "Accessibility in tech",
#   "Blockchain security",
#   "Cryptographic solutions",
#   "Decentralized finance (DeFi)",
#   "Fintech innovation",
#   "Insurtech solutions",
#   "Regtech",
#   "Healthtech platforms",
#   "Digital health",
#   "Telemedicine",
#   "Edtech innovation",
#   "Learning management systems (LMS)",
#   "Proptech solutions",
#   "Smart real estate",
#   "Agtech innovation",
#   "Precision agriculture",
#   "Climate tech solutions",
#   "Renewable energy tech",
#   "Clean energy startups",
#   "Space tech",
#   "Aerospace startups",
#   "Defense tech",
#   "Govtech solutions",
#   "Smart city technology",
#   "Deep tech startups",
#   "Hard tech startups",
#   "Impact startups",
#   "Social impact tech",
#   "Purpose-driven startups",
#   "Sustainability startups",
#   "Femtech",
#   "Gaming startups",
#   "Esports tech",
#   "Creative tech",
#   "Design tech",
#   "Media tech",
#   "Adtech",
#   "Martech",
#   "Sales tech",
#   "Customer success tech",
#   "Product management tools",
#   "HR analytics",
#   "Talent acquisition tech",
#   "Future of education",
#   "Mental health tech",
#   "Wellness tech",
#   "Foodtech innovation",
#   "Supply chain tech",
#   "Logistics tech",
#   "Mobility tech",
#   "Autonomous vehicles",
#   "Drone technology",
#   "Robotics as a Service (RaaS)",
#   "Computer Vision as a Service (CVaaS)",
#   "NLP as a Service (NLPaaS)",
#   "Data as a Service (DaaS)",
#   "API as a Service (APIaaS)",
#   "AI model marketplace",
#   "Vertical AI",
#   "Horizontal AI"
# ]


KEYWORDS = [
        'SaaS', 'MVP', 'early-stage startup', 'prototype', 'software startup',
        'Artificial Intelligence', 'AI-powered', 'Machine Learning', 'Generative AI', 'NLP',
        'Full-stack development', 'Mobile app', 'MERN stack', 'React Native', 'Next.js', 'Flutter',
        'Automation', 'Workflow automation', 'Zapier alternative',
        'Pre-seed', 'Seed funding', 'B2B SaaS', 'YC-backed', 'Tech startup'
    ]


